name: Publication

on:
  push:
    branches: [master]

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Test
        run: |
          git name-rev --name-only --tags HEAD
          echo ====================
          git describe --tags --abbrev=0


      # - name: Setup Scripts ğŸ§©
      #   run: |
      #     pip install -r scripts/requirements.txt
      #     inv env.switch prod
      #     inv tool.install prod --yes

      # - name: Publish ğŸš€
      #   run: inv publish
